# Generated by Django 5.1.7 on 2025-07-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('editado_em', models.DateTimeField(auto_now=True)),
                ('encerrado_em', models.DateTimeField(blank=True, null=True)),
                ('solucao', models.TextField(blank=True, null=True)),
                ('arquivos', models.JSONField(blank=True, default=list)),
                ('analista_id', models.BigIntegerField(blank=True, null=True)),
                ('categoria_id', models.BigIntegerField(blank=True, null=True)),
                ('setor_id', models.BigIntegerField(blank=True, null=True)),
                ('usuario_id', models.BigIntegerField()),
                ('prioridade_id', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
    ]
